server.port=8080
spring.application.name=student-api-springboot

# Springdoc OpenAPI / Swagger UI config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method
springdoc.info.title=CampusConnect Student Management API (Spring Boot)
springdoc.info.version=1.0.0
springdoc.info.description=Lab 3 RESTful Web Services — Spring Boot Implementation
